user/urls.py
from django.urls import path
from django.views.generic import RedirectView

from user.views import (ListActiveUser, ListArchiveUser, MeUser, ShowUser,
                        upload_document)

app_name = 'user'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='user:list-active', permanent=True)),
    path('list/', ListActiveUser.as_view(), name='list-active'),
    path('list/archive', ListArchiveUser.as_view(), name='list-archive'),
    path('me/', MeUser.as_view(), name='me'),
    path('me/upload', upload_document, name='upload'),
    path('show/<int:pk>', ShowUser.as_view(), name='show'),
]

user/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from erp_reloaded.mixins.models import Person


class UploadTo:
    def __init__(self, fieldname):
        self.fieldname = fieldname

    def __call__(self, user, filename):
        _, ext = os.path.splitext(filename)
        ext = ext.lower()
        return f'user/{user.username}/{self.fieldname}{ext}'

    def deconstruct(self):
        return ('user.models.UploadTo', [self.fieldname], {})


def upload_document_to(document, filename):
    _, ext = os.path.splitext(filename)
    ext = ext.lower()
    return f'user/{document.user.username}/{document.name}{ext}'


class User(Person, AbstractUser):
    photo = models.ImageField(upload_to=UploadTo('photo'), null=True, blank=True)
    social_security_number = models.CharField(max_length=64, blank=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    date_left = models.DateField(null=True, blank=True)
    biography = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('user:show', kwargs={'pk': self.pk})

    @property
    def issues(self):
        problems = []
        if not self.social_security_number:
            problems.append("Missing social security number")
        if not self.phone_number:
            problems.append("Missing phone number")
        if not self.email:
            problems.append("Missing email")
        return problems


class DocumentName(models.Model):
    name = models.CharField(max_length=64)
    icon = models.CharField(max_length=32, default="file")

    def __str__(self):
        return self.name


class Document(models.Model):
    name = models.ForeignKey(to='user.DocumentName', on_delete=models.PROTECT)
    user = models.ForeignKey(to='user.User', on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_document_to)

    class Meta:
        unique_together = ('name', 'user')

    def __str__(self):
        return f"{self.user} - {self.name}"

user/forms.py
from django import forms

from user.models import Document, User


class UploadDocumentForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = Document
        fields = ['name', 'file', 'user']

user/views.py
from django.contrib import messages
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, UpdateView
from django_filters import FilterSet, views

from erp_reloaded.forms import InputField, SearchForm
from user.forms import UploadDocumentForm
from user.models import Document, DocumentName, User


class FilterUser(FilterSet):
    class Meta:
        model = User
        fields = ['username']


class ListActiveUser(ListView):
    queryset = User.objects.filter(is_active=True)
    context_object_name = 'user_set'
    template_name = 'user/list-active.html'
    ordering = ['username']


class ListArchiveUser(views.FilterView):
    queryset = User.objects.filter(is_active=False)
    paginate_by = 25
    context_object_name = 'user_set'
    template_name = 'user/list-archive.html'
    filterset_class = FilterUser
    ordering = ['-date_left']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = SearchForm([
            InputField('name'),
        ])
        return context


class ShowUser(UpdateView):
    model = User
    template_name = 'user/show.html'
    context_object_name = 'user'
    fields = ['is_active', 'groups', 'date_left']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()
        return context


class MeUser(UpdateView):
    template_name = 'user/me.html'
    context_object_name = 'user'
    fields = ['first_name', 'last_name', 'email', 'phone_number', 'social_security_number', 'biography', 'photo']

    def get_success_url(self):
        return reverse('user:me')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['document_name_set'] = DocumentName.objects.all()
        return context


# TODO: Protected and served by nginx
def upload_document(request):
    if request.method != 'POST':
        return redirect(reverse('user:me'))
    form = UploadDocumentForm(request.POST, request.FILES)
    if not form.is_valid():
        for field, message in form.errors.items():
            messages.error(request, f"Failed to upload {field}: {message}")
        return redirect(reverse('user:me'))
    form.instance.user = request.user
    old_doc = Document.objects.filter(user=request.user, name=form.instance.name).first()
    if old_doc:
        old_doc.delete()
    document = form.save()
    messages.success(request, f"Uploaded {document.name}")
    return redirect(reverse('user:me'))

templates/user/modals/me.html
<div class="ui modal" id="edit-user-modal">
  <div class="header">Edit {{user.first_name}} {{user.last_name}} profile</div>
  <div class="scrolling content">
    <form id="edit-user-form" action="{% url 'user:me' %}" method="post" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="field">
        <label for="first_name">First name</label>
        <input type="text" name="first_name" value="{{user.first_name}}">
      </div>
      <div class="field">
        <label for="last_name">Last name</label>
        <input type="text" name="last_name" value="{{user.last_name}}">
      </div>
      <div class="field">
        <label for="photo" class="ui icon button">
          <i class="file image icon"></i>
          Photo
        </label>
        <input type="file" id="photo" style="display:none" name="photo">
      </div>
      <div class="field">
        <label for="email">Email</label>
        <input type="email" name="email" value="{{user.email}}">
      </div>
      <div class="field">
        <label for="phone_number">Phone number</label>
        <input type="text" name="phone_number" value="{{user.phone_number}}">
      </div>
      <div class="field">
        <label for="social_security_number">Social security number</label>
        <input type="text" name="social_security_number" value="{{user.social_security_number}}">
      </div>
      <div class="field">
        <label for="biography">Biography</label>
        <textarea name="biography">{{user.biography}}</textarea>
      </div>
    </form>
  </div>
  <div class="actions">
    <button class="ui negative button">Cancel</button>
    <input class="ui positive button" type="submit" form="edit-user-form"/>
  </div>
</div>
<script>
</script>

templates/user/modals/show.html
<div class="ui modal" id="edit-user-modal">
  <div class="header">Edit {{user.full_name}} profile</div>
  <div class="content">
    <form id="edit-user-form" action="{% url 'user:show' user.pk %}" method="post" class="ui form">
    {% csrf_token %}
      <div class="field">
        <label for="groups">Groups</label>
        <select name="groups" multiple="" class="ui fluid dropdown">
          <option value="">Groups</option>
          {% for group in groups %}
          <option value="{{group.pk}}" {% if group in user_groups %}selected{% endif %}>{{group.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="field">
        <div class="ui checkbox">
          <input type="checkbox" name="is_active" {% if user.is_active %}checked{% endif %}>
          <label>User is active</label>
        </div>
      </div>
      <div class="field">
        <div class="ui calendar">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <input type="text" placeholder="Date left" name="date_left" value="{{user.date_left}}" autocomplete="off">
            <button type="button" class="ui icon button" onclick="$('.ui.calendar').calendar({type: 'date', today: true})">
              <i class="redo icon"></i>
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="actions">
    <button class="ui negative button">Cancel</button>
    <input class="ui positive button" type="submit" form="edit-user-form"/>
  </div>
</div>
<script>
$('.ui.calendar').calendar({
  type: 'date',
  today: true,
})
</script>

templates/user/modals/upload.html
<div class="ui modal" id="upload-user-modal">
  <div class="header">Upload a new document</div>
  <div class="content">
    <form action="{% url 'user:upload' %}" method="post" class="ui form" id="upload-user-form" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="field">
        <label for="name">Document type</label>
        <select class="ui dropdown" name="name" id="name">
          <option value="">Document type</option>
          {% for name in document_name_set %}
          <option value="{{name.pk}}">{{name.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="field">
        <label for="file" class="ui icon button">
          <i class="file icon"></i>
          File
        </label>
        <input type="file" id="file" style="display:none" name="file">
      </div>
    </form>
  </div>
  <div class="actions">
    <button class="ui negative button">Cancel</button>
    <input class="ui positive button" type="submit" form="upload-user-form"/>
  </div>
</div>
<script>
</script>