customer/urls.py
from django.urls import path
from django.views.generic import RedirectView

from customer.views import (CreateCustomer, ListCustomer, ShowCustomer,
                            create_contact, create_exchange)

app_name = 'customer'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='customer:list', permanent=True)),
    path('list/', ListCustomer.as_view(), name='list'),
    path('create/', CreateCustomer.as_view(), name='create'),
    path('show/<int:pk>', ShowCustomer.as_view(), name='show'),
    path('show/<int:customer_pk>/create-contact', create_contact, name='create-contact'),
    path('show/<int:customer_pk>/create-exchange', create_exchange, name='create-exchange')
]

user/urls.py
from django.urls import path
from django.views.generic import RedirectView

from user.views import (ListActiveUser, ListArchiveUser, MeUser, ShowUser,
                        upload_document)

app_name = 'user'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='user:list-active', permanent=True)),
    path('list/', ListActiveUser.as_view(), name='list-active'),
    path('list/archive', ListArchiveUser.as_view(), name='list-archive'),
    path('me/', MeUser.as_view(), name='me'),
    path('me/upload', upload_document, name='upload'),
    path('show/<int:pk>', ShowUser.as_view(), name='show'),
]

customer/models.py
import datetime
import os

from django.db import models
from django.shortcuts import reverse
from phonenumber_field.modelfields import PhoneNumberField

from erp_reloaded.mixins.models import Person


def upload_logo_to(customer, filename):
    _, ext = os.path.splitext(filename)
    ext = ext.lower()
    return f'customer/{customer.id}/logo{ext}'


class Customer(models.Model):
    name = models.CharField(max_length=256, unique=True)
    logo = models.ImageField(upload_to=upload_logo_to, null=True, blank=True)
    website = models.URLField(blank=True)
    activity_area_set = models.ManyToManyField(to='customer.ActivityArea')
    size = models.ForeignKey(to='customer.BusinessSize', on_delete=models.PROTECT)
    address = models.CharField(max_length=256, blank=True)
    zip_code = models.CharField(max_length=256, blank=True)
    city = models.CharField(max_length=256, blank=True)
    country = models.ForeignKey(to='customer.Country', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("customer:show", kwargs={"pk": self.pk})

    @property
    def issues(self):
        problems = []
        if self.contact_set.count() == 0:
            problems.append("Customer has no contact")
        if not self.address or not self.zip_code or not self.city:
            problems.append("Customer address incomplete")
        return problems


class Country(models.Model):
    name = models.CharField(max_length=256, unique=True)
    # https://fomantic-ui.com/elements/flag.html
    icon = models.CharField(max_length=8, blank=True)
    value_added_tax = models.DecimalField(decimal_places=4, max_digits=5, default='0.2000')

    def __str__(self):
        return self.name


class ActivityArea(models.Model):
    name = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.name


class BusinessSize(models.Model):
    name = models.CharField(max_length=256, unique=True)
    short = models.CharField(max_length=32, unique=True, blank=True)

    def __str__(self):
        return f"{self.short} - {self.name}"


class Contact(Person, models.Model):
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    office = models.CharField(max_length=256, blank=True)
    email = models.EmailField(blank=True)
    phone_number = PhoneNumberField(blank=True)
    customer = models.ForeignKey(to='customer.Customer', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.customer})"


class Exchange(models.Model):
    class Meta:
        ordering = ['-date', '-id']

    date = models.DateField(default=datetime.date.today)
    contact = models.ForeignKey(to='customer.Contact', on_delete=models.CASCADE)
    user = models.ForeignKey(to='user.User', on_delete=models.SET)
    message = models.TextField()

    def __str__(self):
        return f"{self.contact} @{self.date:%B %d, %Y}"

customer/forms.py
from django import forms

from customer.models import Contact, Exchange


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class ExchangeForm(forms.ModelForm):
    class Meta:
        model = Exchange
        fields = '__all__'

customer/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, UpdateView
from django_filters import FilterSet, views

from customer.forms import ContactForm, ExchangeForm
from customer.models import ActivityArea, BusinessSize, Country, Customer
from erp_reloaded.forms import (CountrySelectField, InputField, SearchForm,
                                SelectField)
from user.models import User


class FilterCustomer(FilterSet):
    class Meta:
        model = Customer
        fields = ['name', 'size', 'country']


class ListCustomer(views.FilterView):
    queryset = Customer.objects.all()
    context_object_name = 'customer_set'
    template_name = 'customer/list.html'
    filterset_class = FilterCustomer
    ordering = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm([
            InputField('name'),
            SelectField('size', options=BusinessSize.objects.all()),
            CountrySelectField("country", options=Country.objects.all(), clearable=True),
        ])
        return context


class CreateCustomer(CreateView):
    model = Customer
    template_name = 'customer/create.html'
    fields = ['name', 'website', 'activity_area_set', 'size', 'address', 'zip_code', 'city', 'country']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activity_area_set'] = ActivityArea.objects.all()
        context['business_size_set'] = BusinessSize.objects.all()
        context['country_set'] = Country.objects.all()
        return context


class ShowCustomer(UpdateView):
    model = Customer
    template_name = 'customer/show.html'
    context_object_name = 'customer'
    fields = ['name', 'website', 'activity_area_set', 'size', 'address', 'zip_code', 'city', 'country']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activity_area_set'] = ActivityArea.objects.all()
        context['business_size_set'] = BusinessSize.objects.all()
        context['country_set'] = Country.objects.all()
        context['contact_set'] = self.object.contact_set.prefetch_related('exchange_set', 'exchange_set__user').all()
        context['user_set'] = User.objects.filter(is_active=True)
        return context


@require_http_methods(["POST"])
def create_contact(request, customer_pk):
    data = request.POST.copy()
    data['customer'] = customer_pk
    form = ContactForm(data)
    if not form.is_valid():
        for field, message in form.errors.items():
            messages.error(request, f"Failed to upload {field}: {message}")
        return redirect(reverse_lazy('customer:show', kwargs={'pk': customer_pk}))
    contact = form.save()
    messages.success(request, f"Contact {contact} created")
    return redirect(reverse_lazy('customer:show', kwargs={'pk': customer_pk}))


@require_http_methods(["POST"])
def create_exchange(request, customer_pk):
    data = request.POST.copy()
    data['customer'] = customer_pk
    form = ExchangeForm(data)
    if not form.is_valid():
        for field, message in form.errors.items():
            messages.error(request, f"Failed to create exchange {field}: {message}")
        return redirect(reverse_lazy('customer:show', kwargs={'pk': customer_pk}))
    exchange = form.save()
    messages.success(request, f"Exchange {exchange} created for customer")
    return redirect(reverse_lazy('customer:show', kwargs={'pk': customer_pk}))

templates/customer/base.html
{% extends 'base.html' %}

{% block app %}
<div class="ui grid">
  <div class="three wide column">
    {% include 'customer/menu.html' %}
  </div>
  <div class="twelve wide column">
    {% block view %}
    {% endblock view %}
  </div>
</div>
{% endblock app %}

templates/customer/create.html
{% extends 'customer/base.html' %}

{% block view %}
<div class="ui segment">
  <h2 class="ui header">Create a customer</h2>

  <form action="{% url 'customer:create' %}" method="post" class="ui form" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="field">
      <label for="name">Name</label>
      <input type="text" name="name" id="name">
    </div>
    <div class="field">
      <label for="website">Website</label>
      <input type="url" name="website" id="website">
    </div>
    <div class="fields">
      <div class="eight wide field">
        <label for="activity_area_set">Activity areas</label>
        <select name="activity_area_set" id="activity_area_set" class="ui fluid multiple search dropdown">
          <option value="">Activity areas</option>
          {% for activity_area in activity_area_set %}
          <option value="{{activity_area.id}}">{{activity_area.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="eight wide field">
        <label for="size">Business size</label>
        <select name="size" id="size" class="ui fluid dropdown">
          <option value="">Business size</option>
          {% for business_size in business_size_set %}
          <option value="{{business_size.id}}">{{business_size.name}}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <h4 class="ui dividing header">Address</h4>

    <div class="field">
      <label for="address">Street</label>
      <input type="text" name="address" id="address">
    </div>
    <div class="fields">
      <div class="four wide field">
        <label for="zip_code">Zip code</label>
        <input type="text" name="zip_code" id="zip_code">
      </div>
      <div class="six wide field">
        <label for="city">City</label>
        <input type="text" name="city" id="city">
      </div>
      <div class="six wide field">
        <label for="country">Country</label>
        <div class="ui search selection dropdown" name="country" id="country">
          <input type="hidden" name="country">
          <i class="dropdown icon"></i>
          <div class="default text">Select Country</div>
          <div class="menu">
            {% for country in country_set %}
              <div class="item" data-value="{{country.id}}"><i class="{{country.icon}} flag"></i>{{country.name}}</div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="field">
      <input type="submit" class="ui button">
    </div>
  </form>
</div>
{% endblock view %}

templates/customer/list.html
{% extends 'customer/base.html' %}

{% block view %}

{% include search_form.template %}

<div class="ui horizontal divider">Customers</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Size</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
  {% for customer in customer_set %}
    <tr class="{% if customer.issues %}error{% endif %}">
      <td><a href="{% url 'customer:show' customer.id %}">{{customer.name}}</a></td>
      <td>
        <i class="{{customer.country.icon}} flag"></i>
        {{customer.country}}
      </td>
      <td>{{customer.size}}</td>
      <td class="right aligned">
        {% if customer.issues %}
        {{customer.issues|first}}
        <div class="ui red label">{{customer.issues|length}}</div>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock view %}

templates/customer/menu.html
<nav class="ui vertical tabular menu">
  <a href="{% url 'customer:list' %}" class="item">Customers</a>
  <a href="{% url 'customer:create' %}" class="item">Create a customer</a>
</nav>

templates/customer/show.html
{% extends 'customer/base.html' %}
{% load static %}
{% load extras %}

{% block view %}

<div class="ui segment">
  <h2 class="ui header">
    {{customer.name}}
    <button id="edit-customer-button" class="ui right floated button">Edit</button>
  </h2>

  <div class="ui items">
    <div class="ui item">
      <div class="image">
      {% if customer.logo %}
        <img src="{{MEDIA_URL}}{{customer.logo}}" alt="User photo" class="ui small right floated image">
      {% else %}
        <img src="{% static 'customer/img/default-customer.png' %}" alt="Default customer logo" class="ui small right floated image">
      {% endif %}
      </div>
      <div class="content">
        <p class="header">{{customer.name}}</p>
        <div class="description">
          <p><i class="chrome icon"></i><a href="{{customer.website}}">{{customer.website}}</a></p>
          <p>
            <i class="certificate icon"></i>
            {% for activity_area in customer.activity_area_set.all %}
            <span class="ui label">{{activity_area.name}}</span>
            {% endfor %}
          </p>
          <p><i class="expand icon"></i>{{customer.size}}</p>
          <p><i class="funnel dollar icon"></i>{{customer.country.value_added_tax|perc}} VAD</p>
        </div>
      </div>
    </div>

    <div class="ui item">
      <div class="content">
        <p class="header"><i class="map marked icon"></i>Address</p>
        <div class="description">
          <p><i class="map marker icon"></i>{{customer.address|default:"No street"}}</p>
          <p>{{customer.zip_code|default:"No zip code"}}</p>
          <p><i class="city icon"></i>{{customer.city|default:"No city"}}</p>
          <p><i class="{{customer.country.icon}} flag"></i>{{customer.country}}</p>
        </div>
      </div>
    </div>

    <button id="create-contact-button" class="ui labeled icon button">
      <i class="add icon"></i>
      Create contact
    </button>

    <button id="create-exchange-button" class="ui labeled icon button">
      <i class="add icon"></i>
      Add Exchange
    </button>
  </div>
</div>

<div class="ui segment">
  <h2 class="ui header">Contacts</h2>
  <div class="ui cards">
  {% for contact in contact_set.all %}
    {% include 'customer/elements/contact-card.html' %}
  {% endfor %}
  </div>
</div>

{% include 'customer/modals/create-contact.html' %}
{% include 'customer/modals/edit.html' %}
{% include 'customer/modals/create-exchange.html' %}

<script>
$('#create-contact-button').click(() => $('#create-contact-modal').modal('show'))
$('#edit-customer-button').click(() => $('#edit-customer-modal').modal('show'))
$('#create-exchange-button').click(() => $('#create-exchange-modal').modal('show'))
</script>
{% endblock view %}