user/urls.py
from django.urls import path
from django.views.generic import RedirectView

from user.views import (ListActiveUser, ListArchiveUser, MeUser, ShowUser,
                        upload_document)

app_name = 'user'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='user:list-active', permanent=True)),
    path('list/', ListActiveUser.as_view(), name='list-active'),
    path('list/archive', ListArchiveUser.as_view(), name='list-archive'),
    path('me/', MeUser.as_view(), name='me'),
    path('me/upload', upload_document, name='upload'),
    path('show/<int:pk>', ShowUser.as_view(), name='show'),
]

user/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from erp_reloaded.mixins.models import Person


class UploadTo:
    def __init__(self, fieldname):
        self.fieldname = fieldname

    def __call__(self, user, filename):
        _, ext = os.path.splitext(filename)
        ext = ext.lower()
        return f'user/{user.username}/{self.fieldname}{ext}'

    def deconstruct(self):
        return ('user.models.UploadTo', [self.fieldname], {})


def upload_document_to(document, filename):
    _, ext = os.path.splitext(filename)
    ext = ext.lower()
    return f'user/{document.user.username}/{document.name}{ext}'


class User(Person, AbstractUser):
    photo = models.ImageField(upload_to=UploadTo('photo'), null=True, blank=True)
    social_security_number = models.CharField(max_length=64, blank=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    date_left = models.DateField(null=True, blank=True)
    biography = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('user:show', kwargs={'pk': self.pk})

    @property
    def issues(self):
        problems = []
        if not self.social_security_number:
            problems.append("Missing social security number")
        if not self.phone_number:
            problems.append("Missing phone number")
        if not self.email:
            problems.append("Missing email")
        return problems


class DocumentName(models.Model):
    name = models.CharField(max_length=64)
    icon = models.CharField(max_length=32, default="file")

    def __str__(self):
        return self.name


class Document(models.Model):
    name = models.ForeignKey(to='user.DocumentName', on_delete=models.PROTECT)
    user = models.ForeignKey(to='user.User', on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_document_to)

    class Meta:
        unique_together = ('name', 'user')

    def __str__(self):
        return f"{self.user} - {self.name}"

user/forms.py
from django import forms

from user.models import Document, User


class UploadDocumentForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = Document
        fields = ['name', 'file', 'user']

user/views.py
from django.contrib import messages
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, UpdateView
from django_filters import FilterSet, views

from erp_reloaded.forms import InputField, SearchForm
from user.forms import UploadDocumentForm
from user.models import Document, DocumentName, User


class FilterUser(FilterSet):
    class Meta:
        model = User
        fields = ['username']


class ListActiveUser(ListView):
    queryset = User.objects.filter(is_active=True)
    context_object_name = 'user_set'
    template_name = 'user/list-active.html'
    ordering = ['username']


class ListArchiveUser(views.FilterView):
    queryset = User.objects.filter(is_active=False)
    paginate_by = 25
    context_object_name = 'user_set'
    template_name = 'user/list-archive.html'
    filterset_class = FilterUser
    ordering = ['-date_left']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = SearchForm([
            InputField('name'),
        ])
        return context


class ShowUser(UpdateView):
    model = User
    template_name = 'user/show.html'
    context_object_name = 'user'
    fields = ['is_active', 'groups', 'date_left']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()
        return context


class MeUser(UpdateView):
    template_name = 'user/me.html'
    context_object_name = 'user'
    fields = ['first_name', 'last_name', 'email', 'phone_number', 'social_security_number', 'biography', 'photo']

    def get_success_url(self):
        return reverse('user:me')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['document_name_set'] = DocumentName.objects.all()
        return context


# TODO: Protected and served by nginx
def upload_document(request):
    if request.method != 'POST':
        return redirect(reverse('user:me'))
    form = UploadDocumentForm(request.POST, request.FILES)
    if not form.is_valid():
        for field, message in form.errors.items():
            messages.error(request, f"Failed to upload {field}: {message}")
        return redirect(reverse('user:me'))
    form.instance.user = request.user
    old_doc = Document.objects.filter(user=request.user, name=form.instance.name).first()
    if old_doc:
        old_doc.delete()
    document = form.save()
    messages.success(request, f"Uploaded {document.name}")
    return redirect(reverse('user:me'))

templates/user/base.html
{% extends 'base.html' %}

{% block app %}
<div class="ui grid">
  <div class="three wide column">
    {% include 'user/menu.html' %}
  </div>
  <div class="twelve wide column">
    {% block view %}
    {% endblock view %}
  </div>
</div>
{% endblock app %}

templates/user/detail.html
{% load static %}
<div class="ui segment {% if not user.is_active %}orange disabled{% endif %}">
  <h2 class="ui header">
    {% if not user.is_active %}
      <span class="ui orange label">Inactive</span>
    {% else %}
      <span class="ui green label">Active</span>
    {% endif %}
    {% if your_profile %}
      Your profile
    {% else %}
      {{user.full_name}}'s profile
    {% endif %}
    <button id="edit-user-button" class="ui right floated button">Edit</button>
  </h2>

  <div class="ui items">
    <div class="ui item">
      <div class="image">
      {% if user.photo %}
        <img src="{{MEDIA_URL}}{{user.photo}}" alt="User photo" class="ui small image">
      {% else %}
        <img src="{% static 'user/img/anonymous-user.png' %}" alt="Anonymous user photo" class="ui small image">
      {% endif %}
      </div>
      <div class="content">
        <p class="header">{{user.full_name}}</p>
        <div class="meta">
          <i class="user circle icon"></i>
          <span>{{user.username}}</span>
        </div>
        <div class="description">
          <p><i class="envelope icon"></i><a href="mailto:{{user.email}}">{{user.email}}</a></p>
          <p><i class="phone icon"></i>{{user.phone_number}}</p>
          <p><i class="medkit icon"></i>{{user.social_security_number}}</p>
          <p><i class="business time icon"></i>In charge from {{user.date_joined|date}} to {{user.date_left|date|default:"-"}}</p>
          <div class="ui labels">
            <i class="users icon"></i>
            {% for group in user_groups %}
              <span class="ui label">{{group.name}}</span>
            {% endfor %}
          </div>
        </div>
        <div class="extra">
          <i class="book icon"></i>
          {{user.biography|default:"No biography"}}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="ui segment {% if not user.is_active %}orange disabled{% endif %}">
  <h2 class="ui header">
    {% if your_profile %}
      Your documents
      <button id="upload-user-button" class="ui right floated button">Upload</a>
    {% else %}
      {{user.full_name}}'s documents
    {% endif %}
    </h2>
  <div>
  {% for document in user.document_set.all %}
    <a href="{{MEDIA_URL}}{{document.file}}" class="ui labeled icon button">
      <i class="{{document.name.icon}} icon"></i>
      {{document.name|upper}}
    </a>
  {% endfor %}
  </div>
</div>

templates/user/list-active.html
{% extends 'user/base.html' %}

{% block view %}
<div class="ui horizontal divider">Active Team</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Groups</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
  {% for user in user_set %}
    <tr class="{% if user.issues %}error{% endif %}">
      <td><a href="{% url 'user:show' user.id %}">@{{user.username}}</a></td>
      <td>{{user.full_name}}</td>
      <td>
      {% for group in user.groups.all %}
        <div class="ui label">{{group.name}}</div>
      {% endfor %}
      </td>
      <td class="right aligned">
        {% if user.issues %}
        {{user.issues|first}}
        <div class="ui red label">{{user.issues|length}}</div>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock view %}

templates/user/list-archive.html
{% extends 'user/base.html' %}

{% block view %}

{% include search_form.template %}

<div class="ui horizontal divider">User archive</div>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Groups</th>
      <th>Date left</th>
    </tr>
  </thead>
  <tbody>
  {% for user in user_set %}
    <tr>
      <td><a href="{% url 'user:show' user.id %}">@{{user.username}}</a></td>
      <td>{{user.full_name}}</td>
      <td>
      {% for group in user.groups.all %}
        <div class="ui label">{{group.name}}</div>
      {% endfor %}
      </td>
      <td>{{user.date_left}}</td>
    </tr>
  {% endfor %}
  <tfoot>
    <tr>
      <td colspan="4">
        <div class="ui pagination menu">
          {% if page_obj.has_previous %}
          <a class="item" href="?page=1">1</a>
          <a class="item" href="?page={{ page_obj.previous_page_number }}"><i class="angle left icon"></i></a>
          {% endif %}

          <div class="active item">{{ page_obj.number }}</div>

          {% if page_obj.paginator.num_pages > page_obj.number %}
          {% if page_obj.has_next %}
          <a class="item" href="?page={{ page_obj.next_page_number }}"><i class="angle right icon"></i></a>
          {% endif %}
          <a class="item" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
          {% endif %}
        </div>
      </td>
    </tr>
  </tfoot>
  </tbody>
</table>
{% endblock view %}

templates/user/me.html
{% extends 'user/base.html' %}

{% block view %}
{% with user.groups.all as user_groups %}

{% with True as your_profile %}
{% include 'user/detail.html' %}
{% include 'user/modals/me.html' %}
{% include 'user/modals/upload.html' %}
{% endwith %}


<script>
$('#edit-user-button').click(() => $('#edit-user-modal').modal('show'))
$('#upload-user-button').click(() => $('#upload-user-modal').modal('show'))
</script>
{% endwith %}
{% endblock view %}

templates/user/menu.html
<nav class="ui vertical tabular menu">
  <a href="{% url 'user:me' %}" class="item">My profile</a>
  <a href="{% url 'user:list-active' %}" class="item">Active team</a>
  <a href="{% url 'user:list-archive' %}" class="item">Old users</a>
</nav>

templates/user/show.html
{% extends 'user/base.html' %}

{% block view %}
{% with user.groups.all as user_groups %}

{% with False as your_profile %}
{% include 'user/detail.html' %}
{% include 'user/modals/show.html' %}
{% endwith %}


<script>
$('#edit-user-button').click(() => $('#edit-user-modal').modal('show'))
</script>
{% endwith %}
{% endblock view %}